### ISSUE TITLE
Hello, wechaty-puppet-puppeteer may support ip proxy in the future?

### ISSUE THREAD

**Issue by waynerQiu** [Chatie/wechaty-puppet-puppeteer#42]
Hello, wechaty-puppet-puppeteer may support ip proxy in the future?
like this:
`  public async initBrowser (proxy?:string): Promise<Browser> {
    log.verbose('PuppetPuppeteerBridge', 'initBrowser()')

    const headless = this.options.head ? false : true
    const browser = await launch({
      args: [
        '--audio-output-channels=0',
        '--disable-default-apps',
        '--disable-extensions',
        '--disable-translate',
        '--disable-gpu',
        '--disable-setuid-sandbox',
        '--disable-sync',
        '--hide-scrollbars',
        '--mute-audio',
        '--no-sandbox',
        /**
         * 新增代理
         */
        '--proxy-server='+proxy
      ],
      headless,
    })`

**Comment by zixia** [comment]
Could you please describe your user case for this feature requirement?

**Comment by fatfatson** [comment]
if too many accounts login under a same IP, they may be locked?

**Comment by huan** [comment]
I'll close this issue because it had been resolved by @sososoyoung from #104
