### ISSUE TITLE
启动项目时提示下载Chromium r588429失败

### ISSUE THREAD

**Issue by mxue12138** [Chatie/wechaty-puppet-puppeteer#44]
`15:44:22 INFO Wechaty <default> start() v0.22.4 is starting...
15:44:22 INFO PuppetManager install(wechaty-puppet-puppeteer@^0.14.1) please wait ...
npm:
> puppeteer@1.8.0 install /Users/mxue/Desktop/works/wechaty_test/node_modules/wechaty/node_modules/puppeteer
> node install.js

npm: ERROR: Failed to download Chromium r588429! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.

npm: { Error: read ETIMEDOUT
    at TLSWrap.onread (net.js:660:25) errno: 'ETIMEDOUT', code: 'ETIMEDOUT', syscall: 'read' }

npm: npm
npm:  WARN wechaty-puppet-puppeteer@0.14.2 requires a peer of file-box@^0.8.22 but none is installed. You must install peer dependencies yourself.
npm WARN wechaty-puppet-puppeteer@0.14.2 requires a peer of wechaty-puppet@^0.14.1 but none is installed. You must install peer dependencies yourself.

npm: npm WARN rx-queue@0.4.28 requires a peer of brolog@^1.4.9 but none is installed. You must install peer dependencies yourself.

npm:

npm: npm
npm: ERR! code ELIFECYCLE

npm: npm ERR! errno 1

npm: npm
npm:  ERR! puppeteer@1.8.0 install: `node install.js`
npm
npm:  ERR! Exit status 1

npm: npm ERR!
npm:
npm ERR! Failed at the puppeteer@1.8.0 install script.

npm: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm:

npm: npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mxue/.npm/_logs/2018-09-07T07_45_17_909Z-debug.log

{ Error: Command failed: npm install wechaty-puppet-puppeteer@^0.14.1
ERROR: Failed to download Chromium r588429! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: read ETIMEDOUT
    at TLSWrap.onread (net.js:660:25) errno: 'ETIMEDOUT', code: 'ETIMEDOUT', syscall: 'read' }
npm WARN wechaty-puppet-puppeteer@0.14.2 requires a peer of file-box@^0.8.22 but none is installed. You must install peer dependencies yourself.
npm WARN wechaty-puppet-puppeteer@0.14.2 requires a peer of wechaty-puppet@^0.14.1 but none is installed. You must install peer dependencies yourself.
npm WARN rx-queue@0.4.28 requires a peer of brolog@^1.4.9 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.8.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mxue/.npm/_logs/2018-09-07T07_45_17_909Z-debug.log

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at Pipe._handle.close (net.js:599:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm install wechaty-puppet-puppeteer@^0.14.1 ' }
15:45:17 ERR Wechaty start() exception: Command failed: npm install wechaty-puppet-puppeteer@^0.14.1
ERROR: Failed to download Chromium r588429! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: read ETIMEDOUT
    at TLSWrap.onread (net.js:660:25) errno: 'ETIMEDOUT', code: 'ETIMEDOUT', syscall: 'read' }
npm WARN wechaty-puppet-puppeteer@0.14.2 requires a peer of file-box@^0.8.22 but none is installed. You must install peer dependencies yourself.
npm WARN wechaty-puppet-puppeteer@0.14.2 requires a peer of wechaty-puppet@^0.14.1 but none is installed. You must install peer dependencies yourself.
npm WARN rx-queue@0.4.28 requires a peer of brolog@^1.4.9 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.8.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mxue/.npm/_logs/2018-09-07T07_45_17_909Z-debug.log

(node:2943) UnhandledPromiseRejectionWarning: Error: Command failed: npm install wechaty-puppet-puppeteer@^0.14.1
ERROR: Failed to download Chromium r588429! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: read ETIMEDOUT
    at TLSWrap.onread (net.js:660:25) errno: 'ETIMEDOUT', code: 'ETIMEDOUT', syscall: 'read' }
npm WARN wechaty-puppet-puppeteer@0.14.2 requires a peer of file-box@^0.8.22 but none is installed. You must install peer dependencies yourself.
npm WARN wechaty-puppet-puppeteer@0.14.2 requires a peer of wechaty-puppet@^0.14.1 but none is installed. You must install peer dependencies yourself.
npm WARN rx-queue@0.4.28 requires a peer of brolog@^1.4.9 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.8.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mxue/.npm/_logs/2018-09-07T07_45_17_909Z-debug.log

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at Pipe._handle.close (net.js:599:12)
(node:2943) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2943) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

wechaty的开发者您好，我在使用您的wecaty插件时出现了一个问题，上面是输出信息，我先复制了您的那6行代码，然后下载wechaty包，下载完了启动就出现这种情况，这个错误信息在mac/windows/centos下都有产生，现在已经排除了网络问题和操作系统问题，请问这个问题应该怎么解决呢

**Comment by zixia** [comment]
It was caused by your network: please make sure you can connect to the global network without any problem.

### Solutions

1. https://github.com/Chatie/wechaty-puppet-puppeteer#note-for-developers-in-china
1. The other solution: use a VPS out of China will fix your issue.

**Comment by mxue12138** [comment]
可是我挂着VPN呢，YouTube/Google/Facebook都可以上，那我用外国的vps试一下，如果不行的我再回复您，谢谢了

**Comment by solarhell** [comment]
```
npm: ERROR: Failed to download Chromium r588429! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.

npm: { Error: read ETIMEDOUT
at TLSWrap.onread (net.js:660:25) errno: 'ETIMEDOUT', code: 'ETIMEDOUT', syscall: 'read' }
```
It shows that your device can't download Chromium.
If you don't want to use proxy in favor of mirror, you may check the README, there is a tip for developers in China mainland.

```
npm: npm
npm: WARN wechaty-puppet-puppeteer@0.14.2 requires a peer of file-box@^0.8.22 but none is installed. You must install peer dependencies yourself.
npm WARN wechaty-puppet-puppeteer@0.14.2 requires a peer of wechaty-puppet@^0.14.1 but none is installed. You must install peer dependencies yourself.
```
For the errors here, you need to run `npm i --save file-box wechaty-puppet` by yourself.

[Links may help](https://yarnpkg.com/lang/zh-hans/docs/dependency-types/#toc-peerdependencies)

**Comment by kuie** [comment]
看了一下源码 阻止默认下载，把需要的chromium 文件 下载路径找到（）直接下载文件后改名字为download-{platform}-{version}放入 xxx/node_modules/puppeteer/.local-chromium/文件夹下 再次安装依赖 需要的chromium 文件就已经放置好了
