### ISSUE TITLE
请问wechaty-puppet-puppeteer怎样使用代理启动

### ISSUE THREAD

**Issue by mxue12138** [Chatie/wechaty-puppet-puppeteer#49]
请问wechaty-puppet-puppeteer怎样使用代理启动？因为服务器ip经常被封禁，所以需要用代理运行wechaty项目，但是我不太清楚怎样传入参数，https://github.com/GoogleChrome/puppeteer/issues/336#issuecomment-323041664
，这是puppeteer传入代理参数的方式，请问您开发的wechaty怎样在启动时向wechaty-puppet-puppeteer传入参数呢?

**Comment by zixia** [comment]
Currently, set proxy to puppeteer is not supported.

However, it will be very easy to support this.

For example, you can pass the `args` to the `puppetOptions`, and then puppet-puppeteer can passed it to puppeteer.

A PR to enable this will be welcome.

**Comment by mxue12138** [comment]
( ⊙ o ⊙ )啊！，那还有没别的办法可以设置代理呢

**Comment by mxue12138** [comment]
> 是的`puppetOptions`，你正在使用的正是我所说的。
> 
> 然而，这个选项还没有被puppet-puppeteer所支持，所以这就是为什么我在谈论“欢迎PR来支持这个新功能”。 😆

那么还有什么办法可以设置代理吗？或者说有什么办法可以解决微信拉黑服务器ip的问题吗？

**Comment by huan** [comment]
I will close this issue because it had been resolved by @sososoyoung from #102
